[colors.primary]
background = "#16121a"
foreground = "#e8dfec"

[colors.normal]
black = "#16121a"
red = "#690005"
green = "#4b4453"
yellow = "#6019ad"
blue = "#450086"
magenta = "#38333c"
cyan = "#563d76"
white = "#793ac7"

[colors.bright]
black = "#e8dfec"
red = "#ffb4ab"
green = "#ffdad3"
yellow = "#eedcff"
blue = "#d8b9ff"
magenta = "#ffb4a4"
cyan = "#ffb4a4"
white = "#e8dfec"
