[colors.primary]
background = "#000000"
foreground = "#9a9a9a"

[colors.cursor]
cursor = "#9a9a9a"

[colors.normal]
black = "#000000"
red = "#2b2925"
green = "#293847"
yellow = "#344d4f"
blue = "#52524b"
magenta = "#55738e"
cyan = "#6c93a6"
white = "#9a9a9a"

[colors.bright]
black = "#363636"
red = "#2b2925"
green = "#293847"
yellow = "#344d4f"
blue = "#52524b"
magenta = "#55738e"
cyan = "#6c93a6"
white = "#9a9a9a"
