general.import = ["~/.cache/m3-colors/colors-alacritty.toml"]

[window]
padding.x = 10
padding.y = 10
decorations = "full"
opacity = 0.90

[font]
size = 10.0

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[cursor]
style = "Block"
